apiVersion: v1
kind: Service
metadata:
  name: tt
  namespace: suxess-it-qa
  labels:
    app: tt
    backstage.io/kubernetes-id: tt
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tt
  type: ClusterIP